package com.dak.backend.controller;

import com.dak.backend.service.SitemapService;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Serves the XML sitemap required by 03 MVP 14.
 *
 * Generated from the database rather than kept as a static file: businesses and
 * updates are added continuously, and a file that has to be regenerated by hand
 * would be stale within a day.
 *
 * Deliberately outside /api/v1 — crawlers look for /sitemap.xml at the site
 * root, and this is a document rather than an API resource.
 */
@RestController
public class SitemapController {

    private final SitemapService sitemapService;

    public SitemapController(SitemapService sitemapService) {
        this.sitemapService = sitemapService;
    }

    @GetMapping(value = "/sitemap.xml", produces = MediaType.APPLICATION_XML_VALUE)
    public String sitemap() {
        return sitemapService.generate();
    }
}